version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mongo-data:


